name: 持续集成与发布

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  检查代码:
    name: 检查代码格式
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 运行 golangci-lint 检查
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --verbose

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'

      - name: 安装前端依赖
        run: |
          cd web
          npm ci

      - name: 运行 ESLint 检查
        run: |
          cd web
          npm install eslint --save-dev
          npx eslint src --ext .js,.vue

  测试:
    name: 运行测试
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 运行 Go 测试
        run: |
          go test ./... -v -cover

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'

      - name: 安装前端依赖
        run: |
          cd web
          npm ci

      - name: 运行前端测试
        run: |
          cd web
          npm install vitest --save-dev
          npx vitest run || echo "暂无前端测试"

  构建:
    name: 构建跨平台程序
    runs-on: ${{ matrix.os }}
    needs: [检查代码, 测试]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary: webdav-sync-linux-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary: webdav-sync-windows-amd64.exe
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary: webdav-sync-macos-amd64
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 构建 Go 二进制文件
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd cmd/server
          go build -o ${{ matrix.binary }}

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'

      - name: 安装前端依赖
        run: |
          cd web
          npm ci

      - name: 构建前端
        run: |
          cd web
          npm run build

      - name: 打包构建产物
        run: |
          mkdir -p artifacts
          cp cmd/server/${{ matrix.binary }} artifacts/
          cp -r web/public artifacts/web
          cd artifacts
          zip -r webdav-sync-${{ matrix.goos }}-${{ matrix.goarch }}.zip .
        shell: bash

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: webdav-sync-${{ matrix.goos }}-${{ matrix.goarch }}
          path: artifacts/webdav-sync-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          retention-days: 7

  发布:
    name: 发布到 GitHub Releases
    runs-on: ubuntu-latest
    needs: 构建
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/webdav-sync-linux-amd64/webdav-sync-linux-amd64.zip
            artifacts/webdav-sync-windows-amd64/webdav-sync-windows-amd64.zip
            artifacts/webdav-sync-macos-amd64/webdav-sync-macos-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}