name: Sync

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types: [published]

jobs:
  调试信息:
    name: 收集调试信息
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打印分支信息
        run: |
          echo "当前分支: $GITHUB_REF_NAME"
          echo "事件: $GITHUB_EVENT_NAME"

      - name: 打印文件列表
        run: |
          ls -R

  检查代码:
    name: 检查代码格式
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 检查 Go 模块
        run: |
          go mod tidy || echo "go.mod 检查失败，可能缺失或不完整"

      - name: 运行 golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --verbose
        continue-on-error: true

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'

      - name: 检查前端目录
        run: |
          if [ -d "web" ]; then
            echo "前端目录存在"
          else
            echo "前端目录缺失"
          fi

      - name: 安装前端依赖
        run: |
          cd web || exit 0
          npm ci || echo "前端依赖安装失败"

      - name: 运行 ESLint
        run: |
          cd web || exit 0
          npm install eslint eslint-plugin-vue --save-dev || echo "ESLint 安装失败"
          npx eslint src --ext .js,.vue || echo "ESLint 检查失败"
        continue-on-error: true

  测试:
    name: 运行测试
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 运行 Go 测试
        run: |
          go test ./... -v -cover || echo "暂无 Go 测试用例或测试失败"

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'

      - name: 运行前端测试
        run: |
          cd web || exit 0
          npm install vitest --save-dev || echo "Vitest 安装失败"
          npx vitest run || echo "暂无前端测试用例或测试失败"
        continue-on-error: true

  构建:
    name: 构建跨平台程序
    runs-on: ${{ matrix.os }}
    needs: [检查代码, 测试]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary: webdav-sync-linux-amd64
            zip_ext: .zip
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary: webdav-sync-windows-amd64.exe
            zip_ext: .zip
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary: webdav-sync-macos-amd64
            zip_ext: .zip
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 检查构建目录
        run: |
          if [ -d "cmd/server" ]; then
            echo "cmd/server 目录存在"
          else
            echo "cmd/server 目录缺失"
            exit 1
          fi

      - name: 构建 Go 二进制文件
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd cmd/server
          go build -o ${{ matrix.binary }}

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package.json'

      - name: 构建前端
        run: |
          if [ -d "web" ]; then
            cd web
            npm ci
            npm run build
          else
            echo "前端目录缺失，跳过前端构建"
          fi

      - name: 打包构建产物
        run: |
          mkdir -p artifacts
          cp cmd/server/${{ matrix.binary }} artifacts/
          if [ -d "web/public" ]; then
            cp -r web/public artifacts/web
          fi
          cd artifacts
          zip -r webdav-sync-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.zip_ext }} .
        shell: bash

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: webdav-sync-${{ matrix.goos }}-${{ matrix.goarch }}
          path: artifacts/webdav-sync-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.zip_ext }}
          retention-days: 7

  发布:
    name: 发布到 GitHub Releases
    runs-on: ubuntu-latest
    needs: 构建
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 准备发布文件
        run: |
          mkdir -p release
          cp artifacts/webdav-sync-linux-amd64/webdav-sync-linux-amd64.zip release/ || echo "Linux 产物缺失"
          cp artifacts/webdav-sync-windows-amd64/webdav-sync-windows-amd64.zip release/ || echo "Windows 产物缺失"
          cp artifacts/webdav-sync-macos-amd64/webdav-sync-macos-amd64.zip release/ || echo "macOS 产物缺失"

      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/webdav-sync-linux-amd64.zip
            release/webdav-sync-windows-amd64.zip
            release/webdav-sync-macos-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}